#version: "3.8"
volumes:
  grafana:

services:

  # Grafana for exploring and visualizing data
  grafana-server:
    image: grafana/grafana:latest
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"

   # Grafana Metrics
  mimir:
    image: grafana/mimir:latest
    depends_on:
      - grafana-server
    volumes:
      - "./mimir/config-single.yaml:/etc/mimir/config.yaml"
    ports:
      - "9009:9009"
    command: [
      "-config.file=/etc/mimir/config.yaml"
    ]

  # Grafana Agent
  grafana-agent:
    image: grafana/agent:latest
    depends_on:
      - mimir
    ports:
      - "12345:12345"
      - "3500:3500"
      - "16603:16603"
    volumes:
      - "./grafana-agent/config.yaml:/etc/agent/agent.yaml"
    command: [
      "-config.file=/etc/agent/agent.yaml",
      "-server.http.address=0.0.0.0:12345",
    ]

  loki:
    image: grafana/loki:latest
    depends_on:
      - grafana-server
    ports:
      - "3100:3100"
    volumes:
      - "./loki/config.yaml:/etc/loki/local-config.yaml"

  vector:
    image: timberio/vector:latest-alpine
    depends_on:
      - loki
    command: --config /etc/vector/vector.toml
    ports:
      - "5114:5114"
    volumes:
      - "./vector:/etc/vector"