
[sources.syslog_tcp5114]
type = "syslog"
address = "0.0.0.0:5114"
mode = "tcp"
#path = "/path/to/socket"

[sources.syslog_udp5115]
type = "syslog"
address = "0.0.0.0:5115"
mode = "udp"

[sinks.loki01]
type = "loki"
inputs = [ "syslog_tcp5114" ]
endpoint = "http://loki:3100"
encoding.codec = "json"
path = "/loki/api/v1/push"
labels = {source="vector"}

[sinks.loki02]
type = "loki"
inputs = [ "syslog_udp5114" ]
endpoint = "http://loki:3100"
encoding.codec = "json"
path = "/loki/api/v1/push"
labels = {source="vector"}
