
[sources.syslog_tcp5114]
type = "syslog"
address = "0.0.0.0:5114"
mode = "tcp"
#path = "/path/to/socket"



[sinks.loki]
type = "loki"
inputs = [ "syslog_tcp5114" ]
endpoint = "http://loki:3100"
encoding.codec = "json"
path = "/loki/api/v1/push"
labels = {source="vector"}


#  [sinks.loki.labels]
#  "\"*\"" = "{{ metadata }}"
#  "\"pod_labels_*\"" = "{{ kubernetes.pod_labels }}"
#  source = "vector"
#  "{{ event_field }}" = "{{ some_other_event_field }}"